spring:
  application:
    name: dummy-axon-test
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/bike_rent
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/bike_rent?authSource=admin
      database: bike_rent
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true